version: '3.8'

services:
  bot:
    build: .
    environment:
      - TOKEN
      - BACKEND_URL
      - PERIODIC_TASK_URL
      - ADMIN_KEY
    restart: unless-stopped
    volumes:
      - ./app.py:/app/app.py
      - ./requirements.txt:/app/requirements.txt
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep 'python app.py' | grep -v grep"]
      interval: 30s
      timeout: 10s
      retries: 3